// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/event/v1/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DomainEvent represents a structured domain event.
// Three-tier queryability:
//   - Envelope fields (always indexed): action, resource_type, resource_id, tenant_id, actor_id, source
//   - Attributes (app-defined indexed k/v): flat string pairs for common filter patterns
//   - Metadata (stored, not queryable): full typed payload as bytes
type DomainEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                           // Assigned by server if empty
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                                                                                   // e.g. "user.created", "document.ingested"
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`                                                   // e.g. "user", "document"
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`                                                         // UUID of affected resource
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                               // Required — partition key
	ActorId       string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`                                                                  // User who caused the event (optional for system events)
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`                                                                                 // Human-readable description
	Attributes    map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Indexed key-value pairs (app-defined, queryable)
	Metadata      []byte                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                               // Full typed payload (JSON, stored but not queryable)
	OccurredAt    int64                  `protobuf:"varint,10,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`                                                       // Unix nanos — when it happened in the source app
	Source        string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`                                                                                  // Set by server from caller cert CN (read-only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	mi := &file_proto_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *DomainEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DomainEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *DomainEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DomainEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DomainEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *DomainEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DomainEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DomainEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DomainEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *DomainEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// EmitRequest contains a single domain event to record.
type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *DomainEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EmitRequest) GetEvent() *DomainEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmitResponse contains the server-assigned event ID.
type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *EmitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EmitBatchRequest contains multiple domain events to record atomically.
type EmitBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DomainEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitBatchRequest) Reset() {
	*x = EmitBatchRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitBatchRequest) ProtoMessage() {}

func (x *EmitBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitBatchRequest.ProtoReflect.Descriptor instead.
func (*EmitBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *EmitBatchRequest) GetEvents() []*DomainEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// EmitBatchResponse contains the server-assigned event IDs.
type EmitBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitBatchResponse) Reset() {
	*x = EmitBatchResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitBatchResponse) ProtoMessage() {}

func (x *EmitBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitBatchResponse.ProtoReflect.Descriptor instead.
func (*EmitBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *EmitBatchResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// QueryEventsRequest retrieves tenant-scoped event history with filtering.
type QueryEventsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Action           string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType     string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId       string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ActorId          string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Source           string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	From             int64                  `protobuf:"varint,7,opt,name=from,proto3" json:"from,omitempty"` // Unix nanos
	To               int64                  `protobuf:"varint,8,opt,name=to,proto3" json:"to,omitempty"`     // Unix nanos
	AttributeFilters map[string]string      `protobuf:"bytes,9,rep,name=attribute_filters,json=attributeFilters,proto3" json:"attribute_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Offset           int32                  `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit            int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *QueryEventsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QueryEventsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QueryEventsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *QueryEventsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *QueryEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *QueryEventsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryEventsRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *QueryEventsRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *QueryEventsRequest) GetAttributeFilters() map[string]string {
	if x != nil {
		return x.AttributeFilters
	}
	return nil
}

func (x *QueryEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// QueryEventsResponse contains the matching events and total count.
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DomainEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *QueryEventsResponse) GetEvents() []*DomainEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SubscribeEventsRequest opens a live stream of events matching envelope-level filters.
// Attribute filtering is not supported on live streams — filter client-side if needed.
type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActionPrefix  string                 `protobuf:"bytes,2,opt,name=action_prefix,json=actionPrefix,proto3" json:"action_prefix,omitempty"` // e.g. "user." matches "user.created", "user.updated"
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeEventsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubscribeEventsRequest) GetActionPrefix() string {
	if x != nil {
		return x.ActionPrefix
	}
	return ""
}

func (x *SubscribeEventsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SubscribeEventsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_proto_event_v1_event_proto protoreflect.FileDescriptor

const file_proto_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/event/v1/event.proto\x12\bevent.v1\"\xa8\x03\n" +
	"\vDomainEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12E\n" +
	"\n" +
	"attributes\x18\b \x03(\v2%.event.v1.DomainEvent.AttributesEntryR\n" +
	"attributes\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\fR\bmetadata\x12\x1f\n" +
	"\voccurred_at\x18\n" +
	" \x01(\x03R\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\vEmitRequest\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.event.v1.DomainEventR\x05event\"\x1e\n" +
	"\fEmitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x10EmitBatchRequest\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.event.v1.DomainEventR\x06events\"%\n" +
	"\x11EmitBatchResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xba\x03\n" +
	"\x12QueryEventsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x12\n" +
	"\x04from\x18\a \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\b \x01(\x03R\x02to\x12_\n" +
	"\x11attribute_filters\x18\t \x03(\v22.event.v1.QueryEventsRequest.AttributeFiltersEntryR\x10attributeFilters\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limit\x1aC\n" +
	"\x15AttributeFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x13QueryEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.event.v1.DomainEventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x97\x01\n" +
	"\x16SubscribeEventsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\raction_prefix\x18\x02 \x01(\tR\factionPrefix\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source2\x99\x02\n" +
	"\fEventService\x125\n" +
	"\x04Emit\x12\x15.event.v1.EmitRequest\x1a\x16.event.v1.EmitResponse\x12D\n" +
	"\tEmitBatch\x12\x1a.event.v1.EmitBatchRequest\x1a\x1b.event.v1.EmitBatchResponse\x12D\n" +
	"\x05Query\x12\x1c.event.v1.QueryEventsRequest\x1a\x1d.event.v1.QueryEventsResponse\x12F\n" +
	"\tSubscribe\x12 .event.v1.SubscribeEventsRequest\x1a\x15.event.v1.DomainEvent0\x01B*Z(github.com/zoobz-io/aegis/proto/event/v1b\x06proto3"

var (
	file_proto_event_v1_event_proto_rawDescOnce sync.Once
	file_proto_event_v1_event_proto_rawDescData []byte
)

func file_proto_event_v1_event_proto_rawDescGZIP() []byte {
	file_proto_event_v1_event_proto_rawDescOnce.Do(func() {
		file_proto_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_v1_event_proto_rawDesc), len(file_proto_event_v1_event_proto_rawDesc)))
	})
	return file_proto_event_v1_event_proto_rawDescData
}

var file_proto_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_event_v1_event_proto_goTypes = []any{
	(*DomainEvent)(nil),            // 0: event.v1.DomainEvent
	(*EmitRequest)(nil),            // 1: event.v1.EmitRequest
	(*EmitResponse)(nil),           // 2: event.v1.EmitResponse
	(*EmitBatchRequest)(nil),       // 3: event.v1.EmitBatchRequest
	(*EmitBatchResponse)(nil),      // 4: event.v1.EmitBatchResponse
	(*QueryEventsRequest)(nil),     // 5: event.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil),    // 6: event.v1.QueryEventsResponse
	(*SubscribeEventsRequest)(nil), // 7: event.v1.SubscribeEventsRequest
	nil,                            // 8: event.v1.DomainEvent.AttributesEntry
	nil,                            // 9: event.v1.QueryEventsRequest.AttributeFiltersEntry
}
var file_proto_event_v1_event_proto_depIdxs = []int32{
	8, // 0: event.v1.DomainEvent.attributes:type_name -> event.v1.DomainEvent.AttributesEntry
	0, // 1: event.v1.EmitRequest.event:type_name -> event.v1.DomainEvent
	0, // 2: event.v1.EmitBatchRequest.events:type_name -> event.v1.DomainEvent
	9, // 3: event.v1.QueryEventsRequest.attribute_filters:type_name -> event.v1.QueryEventsRequest.AttributeFiltersEntry
	0, // 4: event.v1.QueryEventsResponse.events:type_name -> event.v1.DomainEvent
	1, // 5: event.v1.EventService.Emit:input_type -> event.v1.EmitRequest
	3, // 6: event.v1.EventService.EmitBatch:input_type -> event.v1.EmitBatchRequest
	5, // 7: event.v1.EventService.Query:input_type -> event.v1.QueryEventsRequest
	7, // 8: event.v1.EventService.Subscribe:input_type -> event.v1.SubscribeEventsRequest
	2, // 9: event.v1.EventService.Emit:output_type -> event.v1.EmitResponse
	4, // 10: event.v1.EventService.EmitBatch:output_type -> event.v1.EmitBatchResponse
	6, // 11: event.v1.EventService.Query:output_type -> event.v1.QueryEventsResponse
	0, // 12: event.v1.EventService.Subscribe:output_type -> event.v1.DomainEvent
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_event_v1_event_proto_init() }
func file_proto_event_v1_event_proto_init() {
	if File_proto_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_v1_event_proto_rawDesc), len(file_proto_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_v1_event_proto_goTypes,
		DependencyIndexes: file_proto_event_v1_event_proto_depIdxs,
		MessageInfos:      file_proto_event_v1_event_proto_msgTypes,
	}.Build()
	File_proto_event_v1_event_proto = out.File
	file_proto_event_v1_event_proto_goTypes = nil
	file_proto_event_v1_event_proto_depIdxs = nil
}
