// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: mesh_auth.proto

package aegis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenExchangeRequest contains the serialized signed assertion.
type TokenExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assertion     []byte                 `protobuf:"bytes,1,opt,name=assertion,proto3" json:"assertion,omitempty"` // JSON-encoded sctx.SignedAssertion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchangeRequest) Reset() {
	*x = TokenExchangeRequest{}
	mi := &file_mesh_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchangeRequest) ProtoMessage() {}

func (x *TokenExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchangeRequest.ProtoReflect.Descriptor instead.
func (*TokenExchangeRequest) Descriptor() ([]byte, []int) {
	return file_mesh_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TokenExchangeRequest) GetAssertion() []byte {
	if x != nil {
		return x.Assertion
	}
	return nil
}

// TokenExchangeResponse contains the issued token and expiration.
type TokenExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // sctx.SignedToken
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchangeResponse) Reset() {
	*x = TokenExchangeResponse{}
	mi := &file_mesh_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchangeResponse) ProtoMessage() {}

func (x *TokenExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchangeResponse.ProtoReflect.Descriptor instead.
func (*TokenExchangeResponse) Descriptor() ([]byte, []int) {
	return file_mesh_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenExchangeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenExchangeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// RevokeTokenRequest identifies the token to revoke by certificate fingerprint.
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_mesh_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_mesh_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeTokenRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// RevokeTokenResponse is empty on success; errors use gRPC status.
type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_mesh_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_mesh_auth_proto_rawDescGZIP(), []int{3}
}

var File_mesh_auth_proto protoreflect.FileDescriptor

const file_mesh_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fmesh_auth.proto\x12\x05aegis\"4\n" +
	"\x14TokenExchangeRequest\x12\x1c\n" +
	"\tassertion\x18\x01 \x01(\fR\tassertion\"L\n" +
	"\x15TokenExchangeResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"6\n" +
	"\x12RevokeTokenRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\x15\n" +
	"\x13RevokeTokenResponse2\x9c\x01\n" +
	"\bMeshAuth\x12J\n" +
	"\rExchangeToken\x12\x1b.aegis.TokenExchangeRequest\x1a\x1c.aegis.TokenExchangeResponse\x12D\n" +
	"\vRevokeToken\x12\x19.aegis.RevokeTokenRequest\x1a\x1a.aegis.RevokeTokenResponseB\x1bZ\x19github.com/zoobz-io/aegisb\x06proto3"

var (
	file_mesh_auth_proto_rawDescOnce sync.Once
	file_mesh_auth_proto_rawDescData []byte
)

func file_mesh_auth_proto_rawDescGZIP() []byte {
	file_mesh_auth_proto_rawDescOnce.Do(func() {
		file_mesh_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_auth_proto_rawDesc), len(file_mesh_auth_proto_rawDesc)))
	})
	return file_mesh_auth_proto_rawDescData
}

var file_mesh_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mesh_auth_proto_goTypes = []any{
	(*TokenExchangeRequest)(nil),  // 0: aegis.TokenExchangeRequest
	(*TokenExchangeResponse)(nil), // 1: aegis.TokenExchangeResponse
	(*RevokeTokenRequest)(nil),    // 2: aegis.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),   // 3: aegis.RevokeTokenResponse
}
var file_mesh_auth_proto_depIdxs = []int32{
	0, // 0: aegis.MeshAuth.ExchangeToken:input_type -> aegis.TokenExchangeRequest
	2, // 1: aegis.MeshAuth.RevokeToken:input_type -> aegis.RevokeTokenRequest
	1, // 2: aegis.MeshAuth.ExchangeToken:output_type -> aegis.TokenExchangeResponse
	3, // 3: aegis.MeshAuth.RevokeToken:output_type -> aegis.RevokeTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_auth_proto_init() }
func file_mesh_auth_proto_init() {
	if File_mesh_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_auth_proto_rawDesc), len(file_mesh_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mesh_auth_proto_goTypes,
		DependencyIndexes: file_mesh_auth_proto_depIdxs,
		MessageInfos:      file_mesh_auth_proto_msgTypes,
	}.Build()
	File_mesh_auth_proto = out.File
	file_mesh_auth_proto_goTypes = nil
	file_mesh_auth_proto_depIdxs = nil
}
