// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: mesh_auth.proto

package aegis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshAuth_ExchangeToken_FullMethodName = "/aegis.MeshAuth/ExchangeToken"
	MeshAuth_RevokeToken_FullMethodName   = "/aegis.MeshAuth/RevokeToken"
)

// MeshAuthClient is the client API for MeshAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeshAuth provides service-level authentication on the mesh.
// Every node runs this service. Callers connect over mTLS,
// present a SignedAssertion proving private key possession,
// and receive a short-lived SignedToken for subsequent RPC calls.
type MeshAuthClient interface {
	// ExchangeToken exchanges a signed assertion for a service token.
	// The caller's certificate is extracted from the mTLS context.
	ExchangeToken(ctx context.Context, in *TokenExchangeRequest, opts ...grpc.CallOption) (*TokenExchangeResponse, error)
	// RevokeToken revokes a token by certificate fingerprint.
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
}

type meshAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshAuthClient(cc grpc.ClientConnInterface) MeshAuthClient {
	return &meshAuthClient{cc}
}

func (c *meshAuthClient) ExchangeToken(ctx context.Context, in *TokenExchangeRequest, opts ...grpc.CallOption) (*TokenExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenExchangeResponse)
	err := c.cc.Invoke(ctx, MeshAuth_ExchangeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshAuthClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, MeshAuth_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshAuthServer is the server API for MeshAuth service.
// All implementations must embed UnimplementedMeshAuthServer
// for forward compatibility.
//
// MeshAuth provides service-level authentication on the mesh.
// Every node runs this service. Callers connect over mTLS,
// present a SignedAssertion proving private key possession,
// and receive a short-lived SignedToken for subsequent RPC calls.
type MeshAuthServer interface {
	// ExchangeToken exchanges a signed assertion for a service token.
	// The caller's certificate is extracted from the mTLS context.
	ExchangeToken(context.Context, *TokenExchangeRequest) (*TokenExchangeResponse, error)
	// RevokeToken revokes a token by certificate fingerprint.
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	mustEmbedUnimplementedMeshAuthServer()
}

// UnimplementedMeshAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshAuthServer struct{}

func (UnimplementedMeshAuthServer) ExchangeToken(context.Context, *TokenExchangeRequest) (*TokenExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeToken not implemented")
}
func (UnimplementedMeshAuthServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedMeshAuthServer) mustEmbedUnimplementedMeshAuthServer() {}
func (UnimplementedMeshAuthServer) testEmbeddedByValue()                  {}

// UnsafeMeshAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshAuthServer will
// result in compilation errors.
type UnsafeMeshAuthServer interface {
	mustEmbedUnimplementedMeshAuthServer()
}

func RegisterMeshAuthServer(s grpc.ServiceRegistrar, srv MeshAuthServer) {
	// If the following call pancis, it indicates UnimplementedMeshAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshAuth_ServiceDesc, srv)
}

func _MeshAuth_ExchangeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshAuthServer).ExchangeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshAuth_ExchangeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshAuthServer).ExchangeToken(ctx, req.(*TokenExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshAuth_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshAuthServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshAuth_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshAuthServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshAuth_ServiceDesc is the grpc.ServiceDesc for MeshAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.MeshAuth",
	HandlerType: (*MeshAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeToken",
			Handler:    _MeshAuth_ExchangeToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _MeshAuth_RevokeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesh_auth.proto",
}
