// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/common/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizedTenant represents a tenant the user is authorized through
// for the calling application. Returned by identity and session services
// so callers can scope business logic without extra round-trips.
type AuthorizedTenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName    string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                            // janus membership role: viewer, editor, admin, owner
	AppRoles      []string               `protobuf:"bytes,4,rep,name=app_roles,json=appRoles,proto3" json:"app_roles,omitempty"`    // application-defined roles, e.g. ["nexus:editor"]
	AppScopes     []string               `protobuf:"bytes,5,rep,name=app_scopes,json=appScopes,proto3" json:"app_scopes,omitempty"` // application-defined scopes, e.g. ["projects:read", "builds:write"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedTenant) Reset() {
	*x = AuthorizedTenant{}
	mi := &file_proto_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedTenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedTenant) ProtoMessage() {}

func (x *AuthorizedTenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedTenant.ProtoReflect.Descriptor instead.
func (*AuthorizedTenant) Descriptor() ([]byte, []int) {
	return file_proto_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizedTenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthorizedTenant) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *AuthorizedTenant) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthorizedTenant) GetAppRoles() []string {
	if x != nil {
		return x.AppRoles
	}
	return nil
}

func (x *AuthorizedTenant) GetAppScopes() []string {
	if x != nil {
		return x.AppScopes
	}
	return nil
}

var File_proto_common_v1_common_proto protoreflect.FileDescriptor

const file_proto_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/common/v1/common.proto\x12\tcommon.v1\"\xa0\x01\n" +
	"\x10AuthorizedTenant\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\tapp_roles\x18\x04 \x03(\tR\bappRoles\x12\x1d\n" +
	"\n" +
	"app_scopes\x18\x05 \x03(\tR\tappScopesB+Z)github.com/zoobz-io/aegis/proto/common/v1b\x06proto3"

var (
	file_proto_common_v1_common_proto_rawDescOnce sync.Once
	file_proto_common_v1_common_proto_rawDescData []byte
)

func file_proto_common_v1_common_proto_rawDescGZIP() []byte {
	file_proto_common_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_v1_common_proto_rawDesc), len(file_proto_common_v1_common_proto_rawDesc)))
	})
	return file_proto_common_v1_common_proto_rawDescData
}

var file_proto_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_common_v1_common_proto_goTypes = []any{
	(*AuthorizedTenant)(nil), // 0: common.v1.AuthorizedTenant
}
var file_proto_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_v1_common_proto_init() }
func file_proto_common_v1_common_proto_init() {
	if File_proto_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_v1_common_proto_rawDesc), len(file_proto_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_common_v1_common_proto_depIdxs,
		MessageInfos:      file_proto_common_v1_common_proto_msgTypes,
	}.Build()
	File_proto_common_v1_common_proto = out.File
	file_proto_common_v1_common_proto_goTypes = nil
	file_proto_common_v1_common_proto_depIdxs = nil
}
