// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/entitlement/v1/entitlement.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizeApplicationRequest grants a tenant access to the calling application.
type AuthorizeApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActingUserId  string                 `protobuf:"bytes,2,opt,name=acting_user_id,json=actingUserId,proto3" json:"acting_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeApplicationRequest) Reset() {
	*x = AuthorizeApplicationRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeApplicationRequest) ProtoMessage() {}

func (x *AuthorizeApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeApplicationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeApplicationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthorizeApplicationRequest) GetActingUserId() string {
	if x != nil {
		return x.ActingUserId
	}
	return ""
}

// AuthorizeApplicationResponse is empty on success; errors use gRPC status.
type AuthorizeApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeApplicationResponse) Reset() {
	*x = AuthorizeApplicationResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeApplicationResponse) ProtoMessage() {}

func (x *AuthorizeApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeApplicationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{1}
}

// RevokeApplicationRequest revokes a tenant's access to the calling application.
type RevokeApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActingUserId  string                 `protobuf:"bytes,2,opt,name=acting_user_id,json=actingUserId,proto3" json:"acting_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApplicationRequest) Reset() {
	*x = RevokeApplicationRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApplicationRequest) ProtoMessage() {}

func (x *RevokeApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApplicationRequest.ProtoReflect.Descriptor instead.
func (*RevokeApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeApplicationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeApplicationRequest) GetActingUserId() string {
	if x != nil {
		return x.ActingUserId
	}
	return ""
}

// RevokeApplicationResponse is empty on success; errors use gRPC status.
type RevokeApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApplicationResponse) Reset() {
	*x = RevokeApplicationResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApplicationResponse) ProtoMessage() {}

func (x *RevokeApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApplicationResponse.ProtoReflect.Descriptor instead.
func (*RevokeApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{3}
}

// ListTenantApplicationsRequest identifies the tenant to query.
type ListTenantApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantApplicationsRequest) Reset() {
	*x = ListTenantApplicationsRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantApplicationsRequest) ProtoMessage() {}

func (x *ListTenantApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{4}
}

func (x *ListTenantApplicationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListTenantApplicationsResponse contains the authorized applications.
type ListTenantApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*TenantApplication   `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantApplicationsResponse) Reset() {
	*x = ListTenantApplicationsResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantApplicationsResponse) ProtoMessage() {}

func (x *ListTenantApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantApplicationsResponse) GetApplications() []*TenantApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

// TenantApplication represents an application authorized for a tenant.
type TenantApplication struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicationName string                 `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	AuthorizedAt    int64                  `protobuf:"varint,3,opt,name=authorized_at,json=authorizedAt,proto3" json:"authorized_at,omitempty"` // Unix timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TenantApplication) Reset() {
	*x = TenantApplication{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantApplication) ProtoMessage() {}

func (x *TenantApplication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantApplication.ProtoReflect.Descriptor instead.
func (*TenantApplication) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{6}
}

func (x *TenantApplication) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *TenantApplication) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *TenantApplication) GetAuthorizedAt() int64 {
	if x != nil {
		return x.AuthorizedAt
	}
	return 0
}

// GrantUserAccessRequest grants a user access to the calling application.
type GrantUserAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`   // Application-defined roles
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"` // Application-defined scopes
	ActingUserId  string                 `protobuf:"bytes,5,opt,name=acting_user_id,json=actingUserId,proto3" json:"acting_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantUserAccessRequest) Reset() {
	*x = GrantUserAccessRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantUserAccessRequest) ProtoMessage() {}

func (x *GrantUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantUserAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{7}
}

func (x *GrantUserAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GrantUserAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantUserAccessRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GrantUserAccessRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GrantUserAccessRequest) GetActingUserId() string {
	if x != nil {
		return x.ActingUserId
	}
	return ""
}

// GrantUserAccessResponse is empty on success; errors use gRPC status.
type GrantUserAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantUserAccessResponse) Reset() {
	*x = GrantUserAccessResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantUserAccessResponse) ProtoMessage() {}

func (x *GrantUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantUserAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{8}
}

// RevokeUserAccessRequest revokes a user's access to the calling application.
type RevokeUserAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActingUserId  string                 `protobuf:"bytes,3,opt,name=acting_user_id,json=actingUserId,proto3" json:"acting_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserAccessRequest) Reset() {
	*x = RevokeUserAccessRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserAccessRequest) ProtoMessage() {}

func (x *RevokeUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeUserAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeUserAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeUserAccessRequest) GetActingUserId() string {
	if x != nil {
		return x.ActingUserId
	}
	return ""
}

// RevokeUserAccessResponse is empty on success; errors use gRPC status.
type RevokeUserAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserAccessResponse) Reset() {
	*x = RevokeUserAccessResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserAccessResponse) ProtoMessage() {}

func (x *RevokeUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserAccessResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{10}
}

// UpdateUserAccessRequest updates a user's roles and scopes.
type UpdateUserAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`   // Replaces existing roles
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"` // Replaces existing scopes
	ActingUserId  string                 `protobuf:"bytes,5,opt,name=acting_user_id,json=actingUserId,proto3" json:"acting_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAccessRequest) Reset() {
	*x = UpdateUserAccessRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAccessRequest) ProtoMessage() {}

func (x *UpdateUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAccessRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateUserAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserAccessRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UpdateUserAccessRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *UpdateUserAccessRequest) GetActingUserId() string {
	if x != nil {
		return x.ActingUserId
	}
	return ""
}

// UpdateUserAccessResponse is empty on success; errors use gRPC status.
type UpdateUserAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAccessResponse) Reset() {
	*x = UpdateUserAccessResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAccessResponse) ProtoMessage() {}

func (x *UpdateUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAccessResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{12}
}

// ListUserAccessRequest lists users with access in a tenant.
type ListUserAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccessRequest) Reset() {
	*x = ListUserAccessRequest{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccessRequest) ProtoMessage() {}

func (x *ListUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccessRequest.ProtoReflect.Descriptor instead.
func (*ListUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListUserAccessResponse contains users with their roles and scopes.
type ListUserAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserAccess          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccessResponse) Reset() {
	*x = ListUserAccessResponse{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccessResponse) ProtoMessage() {}

func (x *ListUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccessResponse.ProtoReflect.Descriptor instead.
func (*ListUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{14}
}

func (x *ListUserAccessResponse) GetUsers() []*UserAccess {
	if x != nil {
		return x.Users
	}
	return nil
}

// UserAccess represents a user's access to the calling application.
type UserAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	GrantedAt     int64                  `protobuf:"varint,4,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccess) Reset() {
	*x = UserAccess{}
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccess) ProtoMessage() {}

func (x *UserAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entitlement_v1_entitlement_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccess.ProtoReflect.Descriptor instead.
func (*UserAccess) Descriptor() ([]byte, []int) {
	return file_proto_entitlement_v1_entitlement_proto_rawDescGZIP(), []int{15}
}

func (x *UserAccess) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAccess) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserAccess) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *UserAccess) GetGrantedAt() int64 {
	if x != nil {
		return x.GrantedAt
	}
	return 0
}

var File_proto_entitlement_v1_entitlement_proto protoreflect.FileDescriptor

const file_proto_entitlement_v1_entitlement_proto_rawDesc = "" +
	"\n" +
	"&proto/entitlement/v1/entitlement.proto\x12\x0eentitlement.v1\"`\n" +
	"\x1bAuthorizeApplicationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12$\n" +
	"\x0eacting_user_id\x18\x02 \x01(\tR\factingUserId\"\x1e\n" +
	"\x1cAuthorizeApplicationResponse\"]\n" +
	"\x18RevokeApplicationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12$\n" +
	"\x0eacting_user_id\x18\x02 \x01(\tR\factingUserId\"\x1b\n" +
	"\x19RevokeApplicationResponse\"<\n" +
	"\x1dListTenantApplicationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"g\n" +
	"\x1eListTenantApplicationsResponse\x12E\n" +
	"\fapplications\x18\x01 \x03(\v2!.entitlement.v1.TenantApplicationR\fapplications\"\x8a\x01\n" +
	"\x11TenantApplication\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12#\n" +
	"\rauthorized_at\x18\x03 \x01(\x03R\fauthorizedAt\"\xa2\x01\n" +
	"\x16GrantUserAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12$\n" +
	"\x0eacting_user_id\x18\x05 \x01(\tR\factingUserId\"\x19\n" +
	"\x17GrantUserAccessResponse\"u\n" +
	"\x17RevokeUserAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0eacting_user_id\x18\x03 \x01(\tR\factingUserId\"\x1a\n" +
	"\x18RevokeUserAccessResponse\"\xa3\x01\n" +
	"\x17UpdateUserAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12$\n" +
	"\x0eacting_user_id\x18\x05 \x01(\tR\factingUserId\"\x1a\n" +
	"\x18UpdateUserAccessResponse\"4\n" +
	"\x15ListUserAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"J\n" +
	"\x16ListUserAccessResponse\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.entitlement.v1.UserAccessR\x05users\"r\n" +
	"\n" +
	"UserAccess\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"granted_at\x18\x04 \x01(\x03R\tgrantedAt2\xfd\x05\n" +
	"\x12EntitlementService\x12q\n" +
	"\x14AuthorizeApplication\x12+.entitlement.v1.AuthorizeApplicationRequest\x1a,.entitlement.v1.AuthorizeApplicationResponse\x12h\n" +
	"\x11RevokeApplication\x12(.entitlement.v1.RevokeApplicationRequest\x1a).entitlement.v1.RevokeApplicationResponse\x12w\n" +
	"\x16ListTenantApplications\x12-.entitlement.v1.ListTenantApplicationsRequest\x1a..entitlement.v1.ListTenantApplicationsResponse\x12b\n" +
	"\x0fGrantUserAccess\x12&.entitlement.v1.GrantUserAccessRequest\x1a'.entitlement.v1.GrantUserAccessResponse\x12e\n" +
	"\x10RevokeUserAccess\x12'.entitlement.v1.RevokeUserAccessRequest\x1a(.entitlement.v1.RevokeUserAccessResponse\x12e\n" +
	"\x10UpdateUserAccess\x12'.entitlement.v1.UpdateUserAccessRequest\x1a(.entitlement.v1.UpdateUserAccessResponse\x12_\n" +
	"\x0eListUserAccess\x12%.entitlement.v1.ListUserAccessRequest\x1a&.entitlement.v1.ListUserAccessResponseB0Z.github.com/zoobz-io/aegis/proto/entitlement/v1b\x06proto3"

var (
	file_proto_entitlement_v1_entitlement_proto_rawDescOnce sync.Once
	file_proto_entitlement_v1_entitlement_proto_rawDescData []byte
)

func file_proto_entitlement_v1_entitlement_proto_rawDescGZIP() []byte {
	file_proto_entitlement_v1_entitlement_proto_rawDescOnce.Do(func() {
		file_proto_entitlement_v1_entitlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_entitlement_v1_entitlement_proto_rawDesc), len(file_proto_entitlement_v1_entitlement_proto_rawDesc)))
	})
	return file_proto_entitlement_v1_entitlement_proto_rawDescData
}

var file_proto_entitlement_v1_entitlement_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_entitlement_v1_entitlement_proto_goTypes = []any{
	(*AuthorizeApplicationRequest)(nil),    // 0: entitlement.v1.AuthorizeApplicationRequest
	(*AuthorizeApplicationResponse)(nil),   // 1: entitlement.v1.AuthorizeApplicationResponse
	(*RevokeApplicationRequest)(nil),       // 2: entitlement.v1.RevokeApplicationRequest
	(*RevokeApplicationResponse)(nil),      // 3: entitlement.v1.RevokeApplicationResponse
	(*ListTenantApplicationsRequest)(nil),  // 4: entitlement.v1.ListTenantApplicationsRequest
	(*ListTenantApplicationsResponse)(nil), // 5: entitlement.v1.ListTenantApplicationsResponse
	(*TenantApplication)(nil),              // 6: entitlement.v1.TenantApplication
	(*GrantUserAccessRequest)(nil),         // 7: entitlement.v1.GrantUserAccessRequest
	(*GrantUserAccessResponse)(nil),        // 8: entitlement.v1.GrantUserAccessResponse
	(*RevokeUserAccessRequest)(nil),        // 9: entitlement.v1.RevokeUserAccessRequest
	(*RevokeUserAccessResponse)(nil),       // 10: entitlement.v1.RevokeUserAccessResponse
	(*UpdateUserAccessRequest)(nil),        // 11: entitlement.v1.UpdateUserAccessRequest
	(*UpdateUserAccessResponse)(nil),       // 12: entitlement.v1.UpdateUserAccessResponse
	(*ListUserAccessRequest)(nil),          // 13: entitlement.v1.ListUserAccessRequest
	(*ListUserAccessResponse)(nil),         // 14: entitlement.v1.ListUserAccessResponse
	(*UserAccess)(nil),                     // 15: entitlement.v1.UserAccess
}
var file_proto_entitlement_v1_entitlement_proto_depIdxs = []int32{
	6,  // 0: entitlement.v1.ListTenantApplicationsResponse.applications:type_name -> entitlement.v1.TenantApplication
	15, // 1: entitlement.v1.ListUserAccessResponse.users:type_name -> entitlement.v1.UserAccess
	0,  // 2: entitlement.v1.EntitlementService.AuthorizeApplication:input_type -> entitlement.v1.AuthorizeApplicationRequest
	2,  // 3: entitlement.v1.EntitlementService.RevokeApplication:input_type -> entitlement.v1.RevokeApplicationRequest
	4,  // 4: entitlement.v1.EntitlementService.ListTenantApplications:input_type -> entitlement.v1.ListTenantApplicationsRequest
	7,  // 5: entitlement.v1.EntitlementService.GrantUserAccess:input_type -> entitlement.v1.GrantUserAccessRequest
	9,  // 6: entitlement.v1.EntitlementService.RevokeUserAccess:input_type -> entitlement.v1.RevokeUserAccessRequest
	11, // 7: entitlement.v1.EntitlementService.UpdateUserAccess:input_type -> entitlement.v1.UpdateUserAccessRequest
	13, // 8: entitlement.v1.EntitlementService.ListUserAccess:input_type -> entitlement.v1.ListUserAccessRequest
	1,  // 9: entitlement.v1.EntitlementService.AuthorizeApplication:output_type -> entitlement.v1.AuthorizeApplicationResponse
	3,  // 10: entitlement.v1.EntitlementService.RevokeApplication:output_type -> entitlement.v1.RevokeApplicationResponse
	5,  // 11: entitlement.v1.EntitlementService.ListTenantApplications:output_type -> entitlement.v1.ListTenantApplicationsResponse
	8,  // 12: entitlement.v1.EntitlementService.GrantUserAccess:output_type -> entitlement.v1.GrantUserAccessResponse
	10, // 13: entitlement.v1.EntitlementService.RevokeUserAccess:output_type -> entitlement.v1.RevokeUserAccessResponse
	12, // 14: entitlement.v1.EntitlementService.UpdateUserAccess:output_type -> entitlement.v1.UpdateUserAccessResponse
	14, // 15: entitlement.v1.EntitlementService.ListUserAccess:output_type -> entitlement.v1.ListUserAccessResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_entitlement_v1_entitlement_proto_init() }
func file_proto_entitlement_v1_entitlement_proto_init() {
	if File_proto_entitlement_v1_entitlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_entitlement_v1_entitlement_proto_rawDesc), len(file_proto_entitlement_v1_entitlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_entitlement_v1_entitlement_proto_goTypes,
		DependencyIndexes: file_proto_entitlement_v1_entitlement_proto_depIdxs,
		MessageInfos:      file_proto_entitlement_v1_entitlement_proto_msgTypes,
	}.Build()
	File_proto_entitlement_v1_entitlement_proto = out.File
	file_proto_entitlement_v1_entitlement_proto_goTypes = nil
	file_proto_entitlement_v1_entitlement_proto_depIdxs = nil
}
