// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/entitlement/v1/entitlement.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntitlementService_AuthorizeApplication_FullMethodName   = "/entitlement.v1.EntitlementService/AuthorizeApplication"
	EntitlementService_RevokeApplication_FullMethodName      = "/entitlement.v1.EntitlementService/RevokeApplication"
	EntitlementService_ListTenantApplications_FullMethodName = "/entitlement.v1.EntitlementService/ListTenantApplications"
	EntitlementService_GrantUserAccess_FullMethodName        = "/entitlement.v1.EntitlementService/GrantUserAccess"
	EntitlementService_RevokeUserAccess_FullMethodName       = "/entitlement.v1.EntitlementService/RevokeUserAccess"
	EntitlementService_UpdateUserAccess_FullMethodName       = "/entitlement.v1.EntitlementService/UpdateUserAccess"
	EntitlementService_ListUserAccess_FullMethodName         = "/entitlement.v1.EntitlementService/ListUserAccess"
)

// EntitlementServiceClient is the client API for EntitlementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntitlementService provides per-application user management.
// Implemented by janus, consumed by services managing their own users' roles and scopes.
// The calling application is identified by its cert CN. Every write RPC includes
// acting_user_id so janus can verify the actor has admin/owner role in the tenant.
type EntitlementServiceClient interface {
	// AuthorizeApplication grants a tenant access to the calling application.
	AuthorizeApplication(ctx context.Context, in *AuthorizeApplicationRequest, opts ...grpc.CallOption) (*AuthorizeApplicationResponse, error)
	// RevokeApplication revokes a tenant's access to the calling application.
	RevokeApplication(ctx context.Context, in *RevokeApplicationRequest, opts ...grpc.CallOption) (*RevokeApplicationResponse, error)
	// ListTenantApplications lists applications authorized for a tenant.
	ListTenantApplications(ctx context.Context, in *ListTenantApplicationsRequest, opts ...grpc.CallOption) (*ListTenantApplicationsResponse, error)
	// GrantUserAccess grants a user access to the calling application with roles and scopes.
	GrantUserAccess(ctx context.Context, in *GrantUserAccessRequest, opts ...grpc.CallOption) (*GrantUserAccessResponse, error)
	// RevokeUserAccess revokes a user's access to the calling application.
	RevokeUserAccess(ctx context.Context, in *RevokeUserAccessRequest, opts ...grpc.CallOption) (*RevokeUserAccessResponse, error)
	// UpdateUserAccess updates a user's roles and scopes for the calling application.
	UpdateUserAccess(ctx context.Context, in *UpdateUserAccessRequest, opts ...grpc.CallOption) (*UpdateUserAccessResponse, error)
	// ListUserAccess lists users with access to the calling application in a tenant.
	ListUserAccess(ctx context.Context, in *ListUserAccessRequest, opts ...grpc.CallOption) (*ListUserAccessResponse, error)
}

type entitlementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntitlementServiceClient(cc grpc.ClientConnInterface) EntitlementServiceClient {
	return &entitlementServiceClient{cc}
}

func (c *entitlementServiceClient) AuthorizeApplication(ctx context.Context, in *AuthorizeApplicationRequest, opts ...grpc.CallOption) (*AuthorizeApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeApplicationResponse)
	err := c.cc.Invoke(ctx, EntitlementService_AuthorizeApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) RevokeApplication(ctx context.Context, in *RevokeApplicationRequest, opts ...grpc.CallOption) (*RevokeApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeApplicationResponse)
	err := c.cc.Invoke(ctx, EntitlementService_RevokeApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) ListTenantApplications(ctx context.Context, in *ListTenantApplicationsRequest, opts ...grpc.CallOption) (*ListTenantApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantApplicationsResponse)
	err := c.cc.Invoke(ctx, EntitlementService_ListTenantApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GrantUserAccess(ctx context.Context, in *GrantUserAccessRequest, opts ...grpc.CallOption) (*GrantUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantUserAccessResponse)
	err := c.cc.Invoke(ctx, EntitlementService_GrantUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) RevokeUserAccess(ctx context.Context, in *RevokeUserAccessRequest, opts ...grpc.CallOption) (*RevokeUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeUserAccessResponse)
	err := c.cc.Invoke(ctx, EntitlementService_RevokeUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) UpdateUserAccess(ctx context.Context, in *UpdateUserAccessRequest, opts ...grpc.CallOption) (*UpdateUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserAccessResponse)
	err := c.cc.Invoke(ctx, EntitlementService_UpdateUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) ListUserAccess(ctx context.Context, in *ListUserAccessRequest, opts ...grpc.CallOption) (*ListUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserAccessResponse)
	err := c.cc.Invoke(ctx, EntitlementService_ListUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitlementServiceServer is the server API for EntitlementService service.
// All implementations must embed UnimplementedEntitlementServiceServer
// for forward compatibility.
//
// EntitlementService provides per-application user management.
// Implemented by janus, consumed by services managing their own users' roles and scopes.
// The calling application is identified by its cert CN. Every write RPC includes
// acting_user_id so janus can verify the actor has admin/owner role in the tenant.
type EntitlementServiceServer interface {
	// AuthorizeApplication grants a tenant access to the calling application.
	AuthorizeApplication(context.Context, *AuthorizeApplicationRequest) (*AuthorizeApplicationResponse, error)
	// RevokeApplication revokes a tenant's access to the calling application.
	RevokeApplication(context.Context, *RevokeApplicationRequest) (*RevokeApplicationResponse, error)
	// ListTenantApplications lists applications authorized for a tenant.
	ListTenantApplications(context.Context, *ListTenantApplicationsRequest) (*ListTenantApplicationsResponse, error)
	// GrantUserAccess grants a user access to the calling application with roles and scopes.
	GrantUserAccess(context.Context, *GrantUserAccessRequest) (*GrantUserAccessResponse, error)
	// RevokeUserAccess revokes a user's access to the calling application.
	RevokeUserAccess(context.Context, *RevokeUserAccessRequest) (*RevokeUserAccessResponse, error)
	// UpdateUserAccess updates a user's roles and scopes for the calling application.
	UpdateUserAccess(context.Context, *UpdateUserAccessRequest) (*UpdateUserAccessResponse, error)
	// ListUserAccess lists users with access to the calling application in a tenant.
	ListUserAccess(context.Context, *ListUserAccessRequest) (*ListUserAccessResponse, error)
	mustEmbedUnimplementedEntitlementServiceServer()
}

// UnimplementedEntitlementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntitlementServiceServer struct{}

func (UnimplementedEntitlementServiceServer) AuthorizeApplication(context.Context, *AuthorizeApplicationRequest) (*AuthorizeApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeApplication not implemented")
}
func (UnimplementedEntitlementServiceServer) RevokeApplication(context.Context, *RevokeApplicationRequest) (*RevokeApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeApplication not implemented")
}
func (UnimplementedEntitlementServiceServer) ListTenantApplications(context.Context, *ListTenantApplicationsRequest) (*ListTenantApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenantApplications not implemented")
}
func (UnimplementedEntitlementServiceServer) GrantUserAccess(context.Context, *GrantUserAccessRequest) (*GrantUserAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantUserAccess not implemented")
}
func (UnimplementedEntitlementServiceServer) RevokeUserAccess(context.Context, *RevokeUserAccessRequest) (*RevokeUserAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeUserAccess not implemented")
}
func (UnimplementedEntitlementServiceServer) UpdateUserAccess(context.Context, *UpdateUserAccessRequest) (*UpdateUserAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAccess not implemented")
}
func (UnimplementedEntitlementServiceServer) ListUserAccess(context.Context, *ListUserAccessRequest) (*ListUserAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserAccess not implemented")
}
func (UnimplementedEntitlementServiceServer) mustEmbedUnimplementedEntitlementServiceServer() {}
func (UnimplementedEntitlementServiceServer) testEmbeddedByValue()                            {}

// UnsafeEntitlementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntitlementServiceServer will
// result in compilation errors.
type UnsafeEntitlementServiceServer interface {
	mustEmbedUnimplementedEntitlementServiceServer()
}

func RegisterEntitlementServiceServer(s grpc.ServiceRegistrar, srv EntitlementServiceServer) {
	// If the following call pancis, it indicates UnimplementedEntitlementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntitlementService_ServiceDesc, srv)
}

func _EntitlementService_AuthorizeApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).AuthorizeApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_AuthorizeApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).AuthorizeApplication(ctx, req.(*AuthorizeApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_RevokeApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).RevokeApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_RevokeApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).RevokeApplication(ctx, req.(*RevokeApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_ListTenantApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).ListTenantApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_ListTenantApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).ListTenantApplications(ctx, req.(*ListTenantApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GrantUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GrantUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_GrantUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GrantUserAccess(ctx, req.(*GrantUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_RevokeUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).RevokeUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_RevokeUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).RevokeUserAccess(ctx, req.(*RevokeUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_UpdateUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).UpdateUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_UpdateUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).UpdateUserAccess(ctx, req.(*UpdateUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_ListUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).ListUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitlementService_ListUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).ListUserAccess(ctx, req.(*ListUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntitlementService_ServiceDesc is the grpc.ServiceDesc for EntitlementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntitlementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entitlement.v1.EntitlementService",
	HandlerType: (*EntitlementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeApplication",
			Handler:    _EntitlementService_AuthorizeApplication_Handler,
		},
		{
			MethodName: "RevokeApplication",
			Handler:    _EntitlementService_RevokeApplication_Handler,
		},
		{
			MethodName: "ListTenantApplications",
			Handler:    _EntitlementService_ListTenantApplications_Handler,
		},
		{
			MethodName: "GrantUserAccess",
			Handler:    _EntitlementService_GrantUserAccess_Handler,
		},
		{
			MethodName: "RevokeUserAccess",
			Handler:    _EntitlementService_RevokeUserAccess_Handler,
		},
		{
			MethodName: "UpdateUserAccess",
			Handler:    _EntitlementService_UpdateUserAccess_Handler,
		},
		{
			MethodName: "ListUserAccess",
			Handler:    _EntitlementService_ListUserAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/entitlement/v1/entitlement.proto",
}
