// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/session/v1/session.proto

package v1

import (
	v1 "github.com/zoobz-io/aegis/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionEventType identifies the kind of session lifecycle event.
type SessionEventType int32

const (
	SessionEventType_SESSION_EVENT_TYPE_UNSPECIFIED SessionEventType = 0
	SessionEventType_SESSION_EVENT_TYPE_CREATED     SessionEventType = 1
	SessionEventType_SESSION_EVENT_TYPE_REVOKED     SessionEventType = 2
	SessionEventType_SESSION_EVENT_TYPE_EXPIRED     SessionEventType = 3
)

// Enum value maps for SessionEventType.
var (
	SessionEventType_name = map[int32]string{
		0: "SESSION_EVENT_TYPE_UNSPECIFIED",
		1: "SESSION_EVENT_TYPE_CREATED",
		2: "SESSION_EVENT_TYPE_REVOKED",
		3: "SESSION_EVENT_TYPE_EXPIRED",
	}
	SessionEventType_value = map[string]int32{
		"SESSION_EVENT_TYPE_UNSPECIFIED": 0,
		"SESSION_EVENT_TYPE_CREATED":     1,
		"SESSION_EVENT_TYPE_REVOKED":     2,
		"SESSION_EVENT_TYPE_EXPIRED":     3,
	}
)

func (x SessionEventType) Enum() *SessionEventType {
	p := new(SessionEventType)
	*p = x
	return p
}

func (x SessionEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_v1_session_proto_enumTypes[0].Descriptor()
}

func (SessionEventType) Type() protoreflect.EnumType {
	return &file_proto_session_v1_session_proto_enumTypes[0]
}

func (x SessionEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionEventType.Descriptor instead.
func (SessionEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{0}
}

// CreateSessionRequest contains the information needed to create a session.
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateSessionRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// CreateSessionResponse contains the issued session token.
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ValidateSessionRequest contains the session token to validate.
type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateSessionResponse contains validation result and user info if valid.
type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp, 0 if invalid
	Tenants       []*v1.AuthorizedTenant `protobuf:"bytes,4,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_proto_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ValidateSessionResponse) GetTenants() []*v1.AuthorizedTenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

// RevokeSessionRequest identifies the session to revoke.
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RevokeSessionResponse is empty on success; errors use gRPC status.
type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_proto_session_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{5}
}

// RevokeUserSessionsRequest identifies the user whose sessions to revoke.
type RevokeUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsRequest) Reset() {
	*x = RevokeUserSessionsRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsRequest) ProtoMessage() {}

func (x *RevokeUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RevokeUserSessionsResponse contains the count of revoked sessions.
type RevokeUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  uint32                 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsResponse) Reset() {
	*x = RevokeUserSessionsResponse{}
	mi := &file_proto_session_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsResponse) ProtoMessage() {}

func (x *RevokeUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeUserSessionsResponse) GetRevokedCount() uint32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

// ListUserSessionsRequest identifies the user whose sessions to list.
type ListUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsRequest) Reset() {
	*x = ListUserSessionsRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsRequest) ProtoMessage() {}

func (x *ListUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListUserSessionsResponse contains the user's active sessions.
type ListUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsResponse) Reset() {
	*x = ListUserSessionsResponse{}
	mi := &file_proto_session_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsResponse) ProtoMessage() {}

func (x *ListUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// SessionInfo contains information about an active session.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPrefix   string                 `protobuf:"bytes,1,opt,name=token_prefix,json=tokenPrefix,proto3" json:"token_prefix,omitempty"` // First N chars for identification, not full token
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // Unix timestamp
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`      // Unix timestamp
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_session_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *SessionInfo) GetTokenPrefix() string {
	if x != nil {
		return x.TokenPrefix
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// SubscribeSessionEventsRequest configures the event subscription.
type SubscribeSessionEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSessionEventsRequest) Reset() {
	*x = SubscribeSessionEventsRequest{}
	mi := &file_proto_session_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSessionEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSessionEventsRequest) ProtoMessage() {}

func (x *SubscribeSessionEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSessionEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeSessionEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{11}
}

// SessionEvent represents a session lifecycle event.
type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SessionEventType       `protobuf:"varint,1,opt,name=type,proto3,enum=session.v1.SessionEventType" json:"type,omitempty"`
	TokenPrefix   string                 `protobuf:"bytes,2,opt,name=token_prefix,json=tokenPrefix,proto3" json:"token_prefix,omitempty"` // First N chars for identification, not full token
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_proto_session_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_proto_session_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *SessionEvent) GetType() SessionEventType {
	if x != nil {
		return x.Type
	}
	return SessionEventType_SESSION_EVENT_TYPE_UNSPECIFIED
}

func (x *SessionEvent) GetTokenPrefix() string {
	if x != nil {
		return x.TokenPrefix
	}
	return ""
}

func (x *SessionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_session_v1_session_proto protoreflect.FileDescriptor

const file_proto_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/session/v1/session.proto\x12\n" +
	"session.v1\x1a\x1cproto/common/v1/common.proto\"m\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"L\n" +
	"\x15CreateSessionResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\".\n" +
	"\x16ValidateSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x9e\x01\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x125\n" +
	"\atenants\x18\x04 \x03(\v2\x1b.common.v1.AuthorizedTenantR\atenants\",\n" +
	"\x14RevokeSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x17\n" +
	"\x15RevokeSessionResponse\"4\n" +
	"\x19RevokeUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x1aRevokeUserSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\rR\frevokedCount\"2\n" +
	"\x17ListUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x18ListUserSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.session.v1.SessionInfoR\bsessions\"\xac\x01\n" +
	"\vSessionInfo\x12!\n" +
	"\ftoken_prefix\x18\x01 \x01(\tR\vtokenPrefix\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\"\x1f\n" +
	"\x1dSubscribeSessionEventsRequest\"\x9a\x01\n" +
	"\fSessionEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.session.v1.SessionEventTypeR\x04type\x12!\n" +
	"\ftoken_prefix\x18\x02 \x01(\tR\vtokenPrefix\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*\x96\x01\n" +
	"\x10SessionEventType\x12\"\n" +
	"\x1eSESSION_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSESSION_EVENT_TYPE_CREATED\x10\x01\x12\x1e\n" +
	"\x1aSESSION_EVENT_TYPE_REVOKED\x10\x02\x12\x1e\n" +
	"\x1aSESSION_EVENT_TYPE_EXPIRED\x10\x032\xbd\x04\n" +
	"\x0eSessionService\x12T\n" +
	"\rCreateSession\x12 .session.v1.CreateSessionRequest\x1a!.session.v1.CreateSessionResponse\x12Z\n" +
	"\x0fValidateSession\x12\".session.v1.ValidateSessionRequest\x1a#.session.v1.ValidateSessionResponse\x12T\n" +
	"\rRevokeSession\x12 .session.v1.RevokeSessionRequest\x1a!.session.v1.RevokeSessionResponse\x12c\n" +
	"\x12RevokeUserSessions\x12%.session.v1.RevokeUserSessionsRequest\x1a&.session.v1.RevokeUserSessionsResponse\x12]\n" +
	"\x10ListUserSessions\x12#.session.v1.ListUserSessionsRequest\x1a$.session.v1.ListUserSessionsResponse\x12_\n" +
	"\x16SubscribeSessionEvents\x12).session.v1.SubscribeSessionEventsRequest\x1a\x18.session.v1.SessionEvent0\x01B,Z*github.com/zoobz-io/aegis/proto/session/v1b\x06proto3"

var (
	file_proto_session_v1_session_proto_rawDescOnce sync.Once
	file_proto_session_v1_session_proto_rawDescData []byte
)

func file_proto_session_v1_session_proto_rawDescGZIP() []byte {
	file_proto_session_v1_session_proto_rawDescOnce.Do(func() {
		file_proto_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_v1_session_proto_rawDesc), len(file_proto_session_v1_session_proto_rawDesc)))
	})
	return file_proto_session_v1_session_proto_rawDescData
}

var file_proto_session_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_session_v1_session_proto_goTypes = []any{
	(SessionEventType)(0),                 // 0: session.v1.SessionEventType
	(*CreateSessionRequest)(nil),          // 1: session.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),         // 2: session.v1.CreateSessionResponse
	(*ValidateSessionRequest)(nil),        // 3: session.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),       // 4: session.v1.ValidateSessionResponse
	(*RevokeSessionRequest)(nil),          // 5: session.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),         // 6: session.v1.RevokeSessionResponse
	(*RevokeUserSessionsRequest)(nil),     // 7: session.v1.RevokeUserSessionsRequest
	(*RevokeUserSessionsResponse)(nil),    // 8: session.v1.RevokeUserSessionsResponse
	(*ListUserSessionsRequest)(nil),       // 9: session.v1.ListUserSessionsRequest
	(*ListUserSessionsResponse)(nil),      // 10: session.v1.ListUserSessionsResponse
	(*SessionInfo)(nil),                   // 11: session.v1.SessionInfo
	(*SubscribeSessionEventsRequest)(nil), // 12: session.v1.SubscribeSessionEventsRequest
	(*SessionEvent)(nil),                  // 13: session.v1.SessionEvent
	(*v1.AuthorizedTenant)(nil),           // 14: common.v1.AuthorizedTenant
}
var file_proto_session_v1_session_proto_depIdxs = []int32{
	14, // 0: session.v1.ValidateSessionResponse.tenants:type_name -> common.v1.AuthorizedTenant
	11, // 1: session.v1.ListUserSessionsResponse.sessions:type_name -> session.v1.SessionInfo
	0,  // 2: session.v1.SessionEvent.type:type_name -> session.v1.SessionEventType
	1,  // 3: session.v1.SessionService.CreateSession:input_type -> session.v1.CreateSessionRequest
	3,  // 4: session.v1.SessionService.ValidateSession:input_type -> session.v1.ValidateSessionRequest
	5,  // 5: session.v1.SessionService.RevokeSession:input_type -> session.v1.RevokeSessionRequest
	7,  // 6: session.v1.SessionService.RevokeUserSessions:input_type -> session.v1.RevokeUserSessionsRequest
	9,  // 7: session.v1.SessionService.ListUserSessions:input_type -> session.v1.ListUserSessionsRequest
	12, // 8: session.v1.SessionService.SubscribeSessionEvents:input_type -> session.v1.SubscribeSessionEventsRequest
	2,  // 9: session.v1.SessionService.CreateSession:output_type -> session.v1.CreateSessionResponse
	4,  // 10: session.v1.SessionService.ValidateSession:output_type -> session.v1.ValidateSessionResponse
	6,  // 11: session.v1.SessionService.RevokeSession:output_type -> session.v1.RevokeSessionResponse
	8,  // 12: session.v1.SessionService.RevokeUserSessions:output_type -> session.v1.RevokeUserSessionsResponse
	10, // 13: session.v1.SessionService.ListUserSessions:output_type -> session.v1.ListUserSessionsResponse
	13, // 14: session.v1.SessionService.SubscribeSessionEvents:output_type -> session.v1.SessionEvent
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_session_v1_session_proto_init() }
func file_proto_session_v1_session_proto_init() {
	if File_proto_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_v1_session_proto_rawDesc), len(file_proto_session_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_session_v1_session_proto_goTypes,
		DependencyIndexes: file_proto_session_v1_session_proto_depIdxs,
		EnumInfos:         file_proto_session_v1_session_proto_enumTypes,
		MessageInfos:      file_proto_session_v1_session_proto_msgTypes,
	}.Build()
	File_proto_session_v1_session_proto = out.File
	file_proto_session_v1_session_proto_goTypes = nil
	file_proto_session_v1_session_proto_depIdxs = nil
}
