// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proto/identity/v1/identity.proto

package v1

import (
	v1 "github.com/zoobz-io/aegis/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResolveIdentityRequest identifies the external identity to resolve.
type ResolveIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                     // e.g. "github", "google"
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"` // External provider's user ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveIdentityRequest) Reset() {
	*x = ResolveIdentityRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityRequest) ProtoMessage() {}

func (x *ResolveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ResolveIdentityRequest) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

// ResolveIdentityResponse contains the resolved internal user.
type ResolveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // True if a new user was created
	Tenants       []*v1.AuthorizedTenant `protobuf:"bytes,3,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityResponse) Reset() {
	*x = ResolveIdentityResponse{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityResponse) ProtoMessage() {}

func (x *ResolveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveIdentityResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *ResolveIdentityResponse) GetTenants() []*v1.AuthorizedTenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

// RegisterRequest contains the information needed to create a user.
type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Provider       string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"` // e.g. "github", "google"
	ProviderUserId string                 `protobuf:"bytes,5,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	// Optional: create a tenant and assign the user as owner.
	TenantName    string `protobuf:"bytes,6,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	TenantSlug    string `protobuf:"bytes,7,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *RegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterRequest) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *RegisterRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *RegisterRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

// RegisterResponse contains the created user and optional tenant.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Empty if no tenant was requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListProvidersRequest identifies the user whose providers to list.
type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *ListProvidersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListProvidersResponse contains the user's linked OAuth providers.
type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Provider represents a linked external OAuth provider.
type Provider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // e.g. "github", "google"
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	LinkedAt       int64                  `protobuf:"varint,3,opt,name=linked_at,json=linkedAt,proto3" json:"linked_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *Provider) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Provider) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *Provider) GetLinkedAt() int64 {
	if x != nil {
		return x.LinkedAt
	}
	return 0
}

var File_proto_identity_v1_identity_proto protoreflect.FileDescriptor

const file_proto_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	" proto/identity/v1/identity.proto\x12\videntity.v1\x1a\x1cproto/common/v1/common.proto\"^\n" +
	"\x16ResolveIdentityRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\"\x83\x01\n" +
	"\x17ResolveIdentityResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x125\n" +
	"\atenants\x18\x03 \x03(\v2\x1b.common.v1.AuthorizedTenantR\atenants\"\xe2\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x05 \x01(\tR\x0eproviderUserId\x12\x1f\n" +
	"\vtenant_name\x18\x06 \x01(\tR\n" +
	"tenantName\x12\x1f\n" +
	"\vtenant_slug\x18\a \x01(\tR\n" +
	"tenantSlug\"H\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"/\n" +
	"\x14ListProvidersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x15ListProvidersResponse\x123\n" +
	"\tproviders\x18\x01 \x03(\v2\x15.identity.v1.ProviderR\tproviders\"m\n" +
	"\bProvider\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\x12\x1b\n" +
	"\tlinked_at\x18\x03 \x01(\x03R\blinkedAt2\x90\x02\n" +
	"\x0fIdentityService\x12\\\n" +
	"\x0fResolveIdentity\x12#.identity.v1.ResolveIdentityRequest\x1a$.identity.v1.ResolveIdentityResponse\x12G\n" +
	"\bRegister\x12\x1c.identity.v1.RegisterRequest\x1a\x1d.identity.v1.RegisterResponse\x12V\n" +
	"\rListProviders\x12!.identity.v1.ListProvidersRequest\x1a\".identity.v1.ListProvidersResponseB-Z+github.com/zoobz-io/aegis/proto/identity/v1b\x06proto3"

var (
	file_proto_identity_v1_identity_proto_rawDescOnce sync.Once
	file_proto_identity_v1_identity_proto_rawDescData []byte
)

func file_proto_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_proto_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_proto_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_identity_v1_identity_proto_rawDesc), len(file_proto_identity_v1_identity_proto_rawDesc)))
	})
	return file_proto_identity_v1_identity_proto_rawDescData
}

var file_proto_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_identity_v1_identity_proto_goTypes = []any{
	(*ResolveIdentityRequest)(nil),  // 0: identity.v1.ResolveIdentityRequest
	(*ResolveIdentityResponse)(nil), // 1: identity.v1.ResolveIdentityResponse
	(*RegisterRequest)(nil),         // 2: identity.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 3: identity.v1.RegisterResponse
	(*ListProvidersRequest)(nil),    // 4: identity.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),   // 5: identity.v1.ListProvidersResponse
	(*Provider)(nil),                // 6: identity.v1.Provider
	(*v1.AuthorizedTenant)(nil),     // 7: common.v1.AuthorizedTenant
}
var file_proto_identity_v1_identity_proto_depIdxs = []int32{
	7, // 0: identity.v1.ResolveIdentityResponse.tenants:type_name -> common.v1.AuthorizedTenant
	6, // 1: identity.v1.ListProvidersResponse.providers:type_name -> identity.v1.Provider
	0, // 2: identity.v1.IdentityService.ResolveIdentity:input_type -> identity.v1.ResolveIdentityRequest
	2, // 3: identity.v1.IdentityService.Register:input_type -> identity.v1.RegisterRequest
	4, // 4: identity.v1.IdentityService.ListProviders:input_type -> identity.v1.ListProvidersRequest
	1, // 5: identity.v1.IdentityService.ResolveIdentity:output_type -> identity.v1.ResolveIdentityResponse
	3, // 6: identity.v1.IdentityService.Register:output_type -> identity.v1.RegisterResponse
	5, // 7: identity.v1.IdentityService.ListProviders:output_type -> identity.v1.ListProvidersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_identity_v1_identity_proto_init() }
func file_proto_identity_v1_identity_proto_init() {
	if File_proto_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_identity_v1_identity_proto_rawDesc), len(file_proto_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_proto_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_proto_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_proto_identity_v1_identity_proto = out.File
	file_proto_identity_v1_identity_proto_goTypes = nil
	file_proto_identity_v1_identity_proto_depIdxs = nil
}
